version: "3.9"

services:
  web:
    container_name: flygoose-blog-web
    image: ${IMAGE_NAME}:${VERSION}
    env_file:
      - ./.env
    build:
      context: ../
      dockerfile: ./docker/Dockerfile
    ports:
      - "3000:80"
    volumes:
      - ./nginx.conf:/etc/nginx/http.d/default.conf
    restart: on-failure
    networks:
      - flygoose

networks:
  flygoose:
    driver: bridge
